feat: per process state metric
foundation-model-stack/fms-hf-tuning pull request #239
Opened 2024-07-13 15:17 UTC by HarikrishnanBalagopal

### Description of the change

### Related issue number

### How to verify the PR

### Was the PR tested

- [ ] I have added >=1 unit test(s) for every new method I have added.
- [ ] I have ensured all unit tests pass

2024-07-25 08:00 UTC, ashokponkumar approved these changes

2024-07-25 08:00 UTC, ashokponkumar commented
@kmehant please review

2024-07-31 11:36 UTC, kmehant requested changes

2024-07-31 11:36 UTC, kmehant commented on tuning/trainercontroller/controllermetrics/per_process_state.py
> +        return {"rank": rank}
```suggestion
        if torch.distributed.is_available() and torch.distributed.is_initialized():
            return {"rank": torch.distributed.get_rank()}
        return {"rank": None}
```

2024-07-31 11:36 UTC, kmehant commented on tuning/trainercontroller/controllermetrics/per_process_state.py
> +        return {"rank": rank}
optionally you can wrap this again in try and except but the value error should not occur with this check.

2024-08-01 11:15 UTC, kmehant approved these changes
Thank you, process rank centric metric is supported.

2024-08-01 11:19 UTC, kmehant approved these changes
Thank you. Process rank centric state metric is supported.

2024-08-01 11:20 UTC, merged